<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="0" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="113" started-at="2021-03-04T12:02:05Z" finished-at="2021-03-04T12:02:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="113" started-at="2021-03-04T12:02:05Z" finished-at="2021-03-04T12:02:05Z">
      <class name="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01">
        <test-method status="FAIL" signature="setup(java.lang.String)[pri:0, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="setup" is-config="true" duration-ms="0" started-at="2021-03-04T17:32:05Z" finished-at="2021-03-04T17:32:05Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'browser' is required by @Configuration on method setup but has not been marked @Optional or defined
in /tmp/testng-eclipse-1528404305/testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'browser' is required by @Configuration on method setup but has not been marked @Optional or defined
in /tmp/testng-eclipse-1528404305/testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:84)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:201)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="verifyInsufficientVerifier()[pri:1, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyInsufficientVerifier" duration-ms="14" started-at="2021-03-04T17:32:05Z" finished-at="2021-03-04T17:32:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientVerifier -->
        <test-method status="SKIP" signature="verifyInsufficientpendingForFulfilment()[pri:2, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyInsufficientpendingForFulfilment" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyInsufficientVerifier" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyInsufficientpendingForFulfilment()[pri:2, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyInsufficientpendingForFulfilment()[pri:2, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientpendingForFulfilment -->
        <test-method status="SKIP" signature="verifyInsufficiencyFulfillment()[pri:3, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyInsufficiencyFulfillment" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyInsufficientpendingForFulfilment" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyInsufficiencyFulfillment()[pri:3, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyInsufficiencyFulfillment()[pri:3, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficiencyFulfillment -->
        <test-method status="SKIP" signature="verifyInsufficientCasesPresentOrNot()[pri:4, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyInsufficientCasesPresentOrNot" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyInsufficiencyFulfillment" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyInsufficientCasesPresentOrNot()[pri:4, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyInsufficientCasesPresentOrNot()[pri:4, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientCasesPresentOrNot -->
        <test-method status="SKIP" signature="verifyCostApprovalRequiredInsufficient()[pri:5, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyCostApprovalRequiredInsufficient" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyInsufficientCasesPresentOrNot" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyCostApprovalRequiredInsufficient()[pri:5, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyCostApprovalRequiredInsufficient()[pri:5, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCostApprovalRequiredInsufficient -->
        <test-method status="SKIP" signature="verifyApprovalRequiredInsufficient()[pri:6, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyApprovalRequiredInsufficient" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyCostApprovalRequiredInsufficient" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyApprovalRequiredInsufficient()[pri:6, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyApprovalRequiredInsufficient()[pri:6, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyApprovalRequiredInsufficient -->
        <test-method status="SKIP" signature="verifyAdminUserReasonInsufficientBoth()[pri:7, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyAdminUserReasonInsufficientBoth" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyApprovalRequiredInsufficient" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyAdminUserReasonInsufficientBoth()[pri:7, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyAdminUserReasonInsufficientBoth()[pri:7, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAdminUserReasonInsufficientBoth -->
        <test-method status="SKIP" signature="verifyApprovalRequiredAndInsufficientBoth()[pri:8, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifyApprovalRequiredAndInsufficientBoth" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyAdminUserReasonInsufficientBoth" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifyApprovalRequiredAndInsufficientBoth()[pri:8, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifyApprovalRequiredAndInsufficientBoth()[pri:8, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyApprovalRequiredAndInsufficientBoth -->
        <test-method status="SKIP" signature="verifywithdrawCaseStatusClosedByClient()[pri:9, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="verifywithdrawCaseStatusClosedByClient" duration-ms="0" started-at="2021-03-04T17:32:05Z" depends-on-methods="com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01.verifyApprovalRequiredAndInsufficientBoth" finished-at="2021-03-04T17:32:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InsufficientBridgeSme_01.verifywithdrawCaseStatusClosedByClient()[pri:9, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InsufficientBridgeSme_01.verifywithdrawCaseStatusClosedByClient()[pri:9, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifywithdrawCaseStatusClosedByClient -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01@652ce654]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-03-04T17:32:05Z" finished-at="2021-03-04T17:32:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.iBridge.sme.testcases.TC_InsufficientBridgeSme_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
